# Generated by Django 2.2.2 on 2019-06-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_auto_20190618_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='flag_due',
            new_name='is_done',
        ),
    ]
